### Tokenization

Tokenization is the process of breaking down a text into individual words or tokens. This is a fundamental step in natural language processing (NLP) to prepare text for further analysis.

In [20]:
import pandas as pd
import re
from nltk.tokenize import word_tokenize

df = pd.read_csv('/content/genap.csv', sep=';')

def clean_text(text):
    text = re.sub(r'http\S+', '', str(text))
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

df['clean_text'] = df['Data'].apply(clean_text)
df['tokens'] = df['clean_text'].apply(word_tokenize)
display(df[['clean_text', 'tokens']].head())

,clean_text,tokens
0,KOMPAScom Banjir dan longsor yang melanda Ace...,"[KOMPAScom, Banjir, dan, longsor, yang, meland..."
1,nan,[nan]
2,Sumber,[Sumber]
3,nan,[nan]
4,nan,[nan]

In [22]:

"""Case folding converts all characters in the text to a uniform case (usually lowercase) to ensure that words like 'The' and 'the' are treated as the same word."""

df['tokens_lower'] = df['tokens'].apply(lambda x: [word.lower() for word in x])
display(df[['tokens', 'tokens_lower']].head())


"""Stopwords are common words (like 'a', 'the', 'is') that often carry little semantic meaning and can be removed to reduce noise and improve processing efficiency."""

from nltk.corpus import stopwords

stop_words = set(stopwords.words('indonesian')) # Assuming Indonesian text based on previous data

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['tokens_filtered'] = df['tokens_lower'].apply(remove_stopwords)
display(df[['tokens_lower', 'tokens_filtered']].head())


"""Lemmatization is the process of reducing words to their base or dictionary form (lemma). Unlike stemming, which often chops off endings, lemmatization uses a vocabulary and morphological analysis to return a valid word."""

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

df['tokens_lemmatized'] = df['tokens_filtered'].apply(lemmatize_tokens)
display(df[['tokens_filtered', 'tokens_lemmatized']].head())

,tokens,tokens_lower
0,"[KOMPAScom, Banjir, dan, longsor, yang, meland...","[kompascom, banjir, dan, longsor, yang, meland..."
1,[nan],[nan]
2,[Sumber],[sumber]
3,[nan],[nan]
4,[nan],[nan]

,tokens_lower,tokens_filtered
0,"[kompascom, banjir, dan, longsor, yang, meland...","[kompascom, banjir, longsor, melanda, aceh, me..."
1,[nan],[nan]
2,[sumber],[sumber]
3,[nan],[nan]
4,[nan],[nan]

,tokens_filtered,tokens_lemmatized
0,"[kompascom, banjir, longsor, melanda, aceh, me...","[kompascom, banjir, longsor, melanda, aceh, me..."
1,[nan],[nan]
2,[sumber],[sumber]
3,[nan],[nan]
4,[nan],[nan]

### Stemming

"""Stemming is the process of reducing words to their root or base form, often by chopping off prefixes and suffixes. The resulting root may not be a valid word, but it helps in grouping words with similar meanings."""

In [26]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

def stem_tokens(tokens):
    return [stemmer.stem(word) for word in tokens]

df['tokens_stemmed'] = df['tokens_filtered'].apply(stem_tokens)
display(df[['tokens_filtered', 'tokens_stemmed']].head())

,tokens_filtered,tokens_stemmed
0,"[kompascom, banjir, longsor, melanda, aceh, me...","[kompascom, banjir, longsor, melanda, aceh, me..."
1,[nan],[nan]
2,[sumber],[sumber]
3,[nan],[nan]
4,[nan],[nan]

In [24]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('indonesian')) # Menggunakan stopwords bahasa Indonesia

def remove_stopwords(tokens):
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

In [25]:
sample_tokens = ['ini', 'adalah', 'contoh', 'kalimat', 'yang', 'akan', 'difilter']
filtered_sample = remove_stopwords(sample_tokens)
print(f"Original tokens: {sample_tokens}")
print(f"Filtered tokens (no stopwords): {filtered_sample}")

Original tokens: ['ini', 'adalah', 'contoh', 'kalimat', 'yang', 'akan', 'difilter']
Filtered tokens (no stopwords): ['contoh', 'kalimat', 'difilter']

In [27]:
df['tokens_lower'] = df['tokens'].apply(lambda x: [word.lower() for word in x])
display(df[['tokens', 'tokens_lower']].head())

,tokens,tokens_lower
0,"[KOMPAScom, Banjir, dan, longsor, yang, meland...","[kompascom, banjir, dan, longsor, yang, meland..."
1,[nan],[nan]
2,[Sumber],[sumber]
3,[nan],[nan]
4,[nan],[nan]